### PR TITLE
OpenApi

### PR DESCRIPTION
**Pull request by charlesPr**
Implementing OpenApi and restructuring of the pom

### CODE REVIEW

**Comment by charlesPr** [comment]
weh kevin check li

**Review by kevinDalek — COMMENTED** [review]
merge develop into your branch

**Comment by charlesPr** [comment]
weh kevin check ban changement la 
ek si tou bon approve pr la mo kpav merge li

**Comment by kevinDalek** [comment]
Resolve conflicts and merge develop into your branch properly!

**Pull request closed without merging**
